create table VIDEO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50),
	youtuber_id INT,
	lenght INT,
	nb_views INT,
	nb_shares INT,
	nb_like INT,
	nb_dislike INT,
	comments TEXT,
	monetization boolean,
	ads boolean,
constraint fk_video_Youtuber foreign key(youtuber_id) references YOUTUBER(id)
);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (1, 'Nueba Yol', 6, 13, 88036670, 6112371, 5359351, 8635052, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (2, 'This Is the Army', 1, 178, 5801331, 7788823, 3886466, 5448293, 'Fusce posuere felis sed lacus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (3, 'Playing with Love (Puppy Love) (Maladolescenza)', 8, 156, 16733455, 2565909, 3239348, 5257050, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (4, 'Band Wagon, The', 6, 5, 78730151, 1352029, 6388877, 4398628, 'Integer a nibh.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (5, 'Agata and the Storm (Agata e la tempesta)', 5, 5, 59110895, 2059049, 1863278, 5661186, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (6, 'Devil Hides in Doubt (Sollbruchstelle)', 3, 171, 20784284, 416743, 7100253, 2965056, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (7, 'Tale from the Past, A (Përralle Nga e Kaluara)', 5, 134, 10379647, 8932198, 9269886, 8392387, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (8, 'Genghis Blues', 5, 135, 63865155, 4363576, 3873095, 1221841, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (9, 'First Wives Club, The', 4, 137, 43078546, 7108987, 5129701, 219346, 'Quisque ut erat. Curabitur gravida nisi at nibh.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (10, 'Hovering Over the Water (À Flor do Mar)', 8, 22, 19822416, 3540012, 7140116, 7529758, 'Sed ante.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (11, 'House of Dracula', 1, 24, 13643017, 8853962, 5607245, 4387869, 'In quis justo. Maecenas rhoncus aliquam lacus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (12, 'People I Know', 5, 217, 78874323, 7401695, 6822869, 2324263, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (13, 'Keys of the Kingdom, The', 4, 131, 19133621, 429705, 7846764, 9267, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (14, 'Impy''s Island', 10, 120, 28713294, 6193358, 6194438, 2880325, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (15, 'War on Democracy, The', 8, 238, 6010789, 8083868, 828769, 9988685, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (16, 'Tooth & Nail', 3, 97, 7409672, 1560344, 1719074, 5218947, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (17, 'Brown of Harvard', 8, 22, 23025862, 2686428, 7488940, 6973268, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (18, 'Lucky Star', 4, 139, 86169550, 16384, 886729, 7319575, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (19, 'Pursuit of Happiness, The', 10, 157, 34616035, 6973075, 3126666, 3612597, 'Aliquam erat volutpat. In congue.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (20, 'Panda! Go Panda! Rainy Day Circus', 8, 91, 46027799, 248803, 2473331, 1549892, 'Duis consequat dui nec nisi volutpat eleifend.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (21, 'Free Men (Les hommes libres)', 7, 201, 77674804, 3522374, 9021064, 7977991, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (22, 'Just Imagine', 1, 118, 38146027, 5078219, 7218315, 1630864, 'Sed ante.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (23, 'Six Pack', 10, 42, 72475696, 2381883, 9733975, 1162248, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (24, 'Play Girl', 1, 6, 28551858, 2222021, 1342901, 5294005, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (25, 'Blade of the Ripper', 5, 255, 21430984, 7737183, 7820964, 7138103, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (26, 'Mysteries of Lisbon (Mistérios de Lisboa)', 10, 185, 440047, 2553196, 905457, 5464835, 'Nulla nisl.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (27, 'Bullets or Ballots', 4, 230, 41850134, 6648699, 9439950, 4831216, 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (28, 'Opposing Force', 4, 132, 40260331, 7947553, 8273093, 634325, 'Maecenas ut massa quis augue luctus tincidunt.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (29, 'Dragon Ball Z: Cooler''s Revenge (Doragon bôru Z 5: Tobikkiri no saikyô tai saikyô)', 10, 44, 92816961, 4787229, 521601, 3896189, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (30, 'I''m a Cyborg, But That''s OK (Saibogujiman kwenchana)', 8, 120, 11158755, 4463908, 2154975, 970975, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (31, 'Child''s Play 2', 5, 187, 62974769, 1069729, 2272334, 6322406, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (32, 'I Love Trouble', 4, 183, 26679371, 8718951, 7657161, 9657379, 'In blandit ultrices enim.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (33, 'Off the Black', 4, 25, 89062487, 8230067, 8887190, 931334, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (34, 'Just Like Me (Igualita a Mi)', 3, 51, 96330426, 5620336, 9460848, 3350482, 'Suspendisse accumsan tortor quis turpis.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (35, 'How I Live Now', 9, 123, 12631143, 2020957, 4384292, 2004159, 'Nullam varius. Nulla facilisi.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (36, 'Super Bitch', 6, 173, 92441955, 9562744, 8669170, 1622856, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (37, '¡Alambrista! (Illegal, The)', 2, 170, 16571168, 4503709, 2530303, 6758257, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (38, 'Mountain, The', 2, 117, 17967, 1813525, 7452708, 9064235, 'Nunc purus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (39, 'Edison, the Man', 2, 116, 86742544, 7575888, 5298510, 5487119, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (40, 'Love Guru, The', 10, 243, 91313200, 3056304, 7341340, 5889320, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (41, 'Human Trafficking', 10, 85, 96443749, 3095264, 7220458, 7729135, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (42, 'Stay Alive', 3, 181, 18837893, 8493977, 300088, 9068058, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (43, 'Meek''s Cutoff', 7, 165, 94678659, 8368882, 1086293, 8497871, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (44, 'Out of Towners, The', 3, 39, 91236176, 3287929, 9428115, 8819692, 'Phasellus sit amet erat. Nulla tempus.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (45, 'Sniper, The', 6, 94, 89463992, 1797096, 5929773, 3913988, 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (46, 'Shark Night 3D', 2, 21, 88676549, 5890897, 2790439, 5954866, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (47, 'Mahakaal (The Monster)', 4, 18, 94619051, 1568420, 1864175, 502244, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (48, 'Juche Idea, The', 10, 226, 7184203, 30861, 2729776, 9601178, 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (49, 'Hope Springs', 6, 224, 98824063, 2607943, 4900096, 7781703, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (50, 'Troll Hunter, The (Trolljegeren)', 10, 180, 10106107, 7927638, 5328629, 5851617, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (51, 'Gone Baby Gone', 6, 108, 63335394, 7813401, 3781630, 7995007, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (52, 'Escape Artist, The', 4, 189, 39288776, 3134838, 7423322, 5399048, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (53, 'Billy Elliot', 5, 202, 62566797, 5710008, 3338270, 1674645, 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (54, 'Unmade Beds', 7, 83, 61046722, 6451270, 733047, 755629, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (55, 'Green Years, The', 8, 178, 76434463, 8654001, 2017401, 5430466, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (56, 'Flintstone Kids'' Just Say No Special, The', 10, 72, 70721486, 4208259, 9547242, 4498489, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (57, 'How High', 3, 105, 43990232, 5039034, 7801664, 6827042, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (58, 'Bird', 9, 246, 88519480, 5447287, 5746239, 74687, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (59, 'Tiger and the Snow, The (La tigre e la neve)', 2, 130, 8196022, 9225587, 4361851, 21927, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (60, 'Gunless', 4, 38, 16206228, 671471, 4096849, 8240597, 'Donec dapibus.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (61, 'Snoopy Come Home', 2, 26, 19920532, 2287295, 7349556, 4491837, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (62, 'Saw IV', 5, 28, 50175079, 6725022, 916192, 7679529, 'Duis ac nibh.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (63, 'Bakery Girl of Monceau, The (La boulangère de Monceau)', 2, 228, 52988051, 9000349, 9034022, 929733, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (64, 'Dummy', 1, 93, 76974181, 5453475, 3550780, 3174065, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (65, 'Daddy Day Care', 10, 104, 6479578, 2486543, 7945754, 318028, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (66, 'American Nightmare, The', 6, 229, 34017455, 1859327, 5117888, 7851408, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (67, 'How I Live Now', 1, 6, 55639494, 2233528, 5347080, 2291487, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (68, 'Nothing Left to Fear', 9, 3, 64191287, 6081581, 471717, 3185157, 'In quis justo. Maecenas rhoncus aliquam lacus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (69, 'Geographer Drank His Globe Away, The (Geograf globus propil)', 4, 101, 75664425, 8359994, 7095152, 2047102, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (70, 'Daredevil', 9, 95, 64657507, 743404, 2633183, 2562250, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (71, 'Goodbye Charlie', 2, 85, 21071810, 2001490, 1627036, 5192531, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (72, 'Life On A String (Bian chang Bian Zou)', 6, 251, 11322959, 1890234, 5264497, 6481395, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (73, 'Girl in the Park, The', 4, 203, 4964813, 3788417, 9854188, 6189067, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (74, 'Two Can Play That Game', 9, 178, 83064773, 2945669, 1536388, 8234281, 'Pellentesque eget nunc.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (75, 'Stonehenge Apocalypse', 5, 182, 57710591, 9564729, 1249520, 17216, 'Maecenas ut massa quis augue luctus tincidunt.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (76, 'Hello Down There', 8, 220, 98705924, 3595506, 3444530, 226312, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (77, 'Bedknobs and Broomsticks', 3, 141, 72222333, 2020328, 5362033, 2933147, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (78, 'Ingrid', 7, 204, 83567480, 3468927, 5875905, 8227861, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (79, 'Mac & Devin Go to High School', 1, 46, 8293464, 997728, 8349260, 3007435, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (80, 'Silent Sonata', 3, 48, 88576864, 966244, 6056994, 9975289, 'Aliquam non mauris.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (81, 'Deep Blue Sea, The', 10, 214, 26882119, 8846483, 6980136, 4731367, 'Aenean lectus.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (82, 'Primrose Path', 7, 134, 21200606, 3433889, 29704, 1350706, 'Suspendisse ornare consequat lectus.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (83, 'Scarecrows', 4, 108, 14502370, 2119025, 9122276, 4081988, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (84, 'Caught', 9, 12, 83655274, 2201959, 5657938, 2794642, 'Nulla suscipit ligula in lacus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (85, 'Gulliver''s Travels', 4, 165, 4063571, 9313372, 1241164, 3196537, 'Cras in purus eu magna vulputate luctus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (86, 'Enter the Phoenix (Da lao ai mei li)', 3, 29, 8837920, 256783, 343562, 4363082, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (87, 'Bowery at Midnight', 7, 248, 94638353, 4456014, 1751449, 4868693, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (88, 'From Hell', 8, 74, 69196420, 9454534, 139248, 8218170, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (89, 'Tokyo Trial (Tokyo saiban)', 4, 249, 83582064, 5475902, 6582649, 6157443, 'Etiam faucibus cursus urna.', false, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (90, 'Goodbye, Mr. Chips', 4, 124, 77690367, 1450298, 3287242, 7833363, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (91, 'Hoop Realities', 2, 181, 45610208, 7855124, 7623171, 5388344, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (92, 'Lonesome', 1, 146, 41232383, 3380667, 9095917, 6239364, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', true, false);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (93, 'Behind the Sun (Abril Despedaçado)', 2, 245, 70678569, 2656724, 2484115, 3337752, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (94, 'Reform School Girls', 1, 184, 8625925, 9976235, 3845012, 2777471, 'Aenean lectus.', false, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (95, 'Marooned', 8, 88, 23670233, 2000170, 9901133, 8341962, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (96, 'Hell Ride', 4, 58, 2274820, 366277, 8189498, 1749688, 'Pellentesque ultrices mattis odio.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (97, 'D2: The Mighty Ducks', 4, 188, 98134201, 3304888, 3615345, 4430661, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (98, 'How to Be a Man', 4, 133, 33752668, 9946326, 6537805, 1125980, 'Nam nulla.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (99, 'Battle Creek Brawl (Big Brawl, The)', 10, 230, 62966846, 125885, 9816252, 4992216, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', true, true);
insert into VIDEO (id, name, youtuber_id, lenght, nb_views, nb_shares, nb_like, nb_dislike, comments, monetization, ads) values (100, 'Ulysses (Ulisse)', 6, 227, 72362626, 8730499, 4597303, 2068480, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', true, false);
